#pragma once

#define WELCOME_MSG "Bem vindo ao visualizador de imagens do desafio Pixeon!"
#define OPEN_FILE_MSG "Abrir arquivo"
#define SAVE_FILE_AS_MSG "Salvar arquivo como"
#define NO_IMG_IN_CLIPBOARD_MSG "Não há nenhuma imagem na área de transferência"
#define IMG_FROM_CLIPBOARD_MSG "Imagem carregada da área de transferência. %1x%2, Profundidade: %3"

#define FILE_LBL "Arquivo"
#define OPEN_FILE_LBL "Abrir..."
#define SAVE_FILE_LBL "Salvar"
#define SAVE_AS_FILE_LBL "Salvar como..."
#define CLOSE_IMG_LBL "Fechar imagem"
#define EXIT_LBL "Sair"
#define EDIT_LBL "Editar"
#define COPY_LBL "Copiar"
#define PASTE_LBL "Colar"
#define ROTATE_CW_LBL "Rotacionar (sentido horário)"
#define ROTATE_CCW_LBL "Rotacionar (sentido anti-horário)"
#define RESCALE_LBL "Redimensionar"
#define ADJUST_BRIGHT_LBL "Ajustar brilho"
#define ADJUST_CONTR_LBL "Ajustar contraste"
#define VIEW_LBL "Visualizar"
#define ZOOM_IN_LBL "Mais Zoom"
#define ZOOM_OUT_LBL "Menos Zoom"
#define ORIGINAL_SIZE_LBL "Tamanho original"
#define FIT_WINDOW_LBL "Encaixar na tela"
#define HELP_LBL "Ajuda"
#define ABOUT_LBL "Sobre"
